namespace AshaNandanvan.Application.DogSitting;

public static class DogBreedCatalog
{
    public static IReadOnlyList<string> All { get; } =
    [
        "Affenpinscher",
        "Afghan Hound",
        "Airedale Terrier",
        "Akita",
        "Alaskan Malamute",
        "American Bulldog",
        "American Pit Bull Terrier",
        "American Staffordshire Terrier",
        "Australian Cattle Dog",
        "Australian Kelpie",
        "Australian Shepherd",
        "Australian Silky Terrier",
        "Australian Terrier",
        "Basenji",
        "Basset Hound",
        "Beagle",
        "Bearded Collie",
        "Belgian Malinois",
        "Belgian Shepherd",
        "Bernese Mountain Dog",
        "Bichon Frise",
        "Bloodhound",
        "Border Collie",
        "Border Terrier",
        "Borzoi",
        "Boston Terrier",
        "Boxer",
        "Briard",
        "British Bulldog",
        "Bull Terrier",
        "Bullmastiff",
        "Cairn Terrier",
        "Cane Corso",
        "Cavalier King Charles Spaniel",
        "Cavoodle",
        "Chihuahua",
        "Chow Chow",
        "Cocker Spaniel",
        "Collie",
        "Corgi",
        "Dachshund",
        "Dalmatian",
        "Dingo",
        "Dobermann",
        "Dogo Argentino",
        "Dogue de Bordeaux",
        "English Setter",
        "English Springer Spaniel",
        "Fila Brasileiro",
        "Fox Terrier",
        "French Bulldog",
        "German Shepherd",
        "German Shorthaired Pointer",
        "Giant Schnauzer",
        "Golden Retriever",
        "Goldendoodle",
        "Great Dane",
        "Greyhound",
        "Groodle",
        "Hungarian Vizsla",
        "Irish Setter",
        "Irish Wolfhound",
        "Italian Greyhound",
        "Jack Russell Terrier",
        "Japanese Tosa",
        "Japanese Spitz",
        "Keeshond",
        "Kelpie",
        "Labradoodle",
        "Labrador Retriever",
        "Lagotto Romagnolo",
        "Leonberger",
        "Lhasa Apso",
        "Maltese",
        "Maltipoo",
        "Mastiff",
        "Miniature Dachshund",
        "Miniature Pinscher",
        "Miniature Schnauzer",
        "Mixed / Cross",
        "Newfoundland",
        "Old English Sheepdog",
        "Papillon",
        "Pekingese",
        "Perro de Presa Canario",
        "Pembroke Welsh Corgi",
        "Pit Bull Terrier",
        "Pointer",
        "Pomeranian",
        "Poodle",
        "Pug",
        "Puggle",
        "Rhodesian Ridgeback",
        "Rottweiler",
        "Saint Bernard",
        "Saluki",
        "Samoyed",
        "Schipperke",
        "Schnauzer",
        "Scottish Terrier",
        "Shar Pei",
        "Shetland Sheepdog",
        "Shiba Inu",
        "Shih Tzu",
        "Siberian Husky",
        "Spoodle",
        "Staffordshire Bull Terrier",
        "Standard Poodle",
        "Tenterfield Terrier",
        "Tibetan Spaniel",
        "Tibetan Terrier",
        "Toy Poodle",
        "Weimaraner",
        "Welsh Springer Spaniel",
        "West Highland White Terrier",
        "Whippet",
        "White Swiss Shepherd",
        "Yorkshire Terrier"
    ];

    /// <summary>
    /// Restricted import breeds in Australia, plus giant or guardian breeds
    /// that do not suit a shared backyard with hens and other dogs.
    /// </summary>
    private static readonly HashSet<string> NoSitting = new(StringComparer.OrdinalIgnoreCase)
    {
        "Akita",
        "American Bulldog",
        "American Pit Bull Terrier",
        "American Staffordshire Terrier",
        "Belgian Malinois",
        "Bullmastiff",
        "Cane Corso",
        "Dingo",
        "Dobermann",
        "Dogo Argentino",
        "Dogue de Bordeaux",
        "Fila Brasileiro",
        "Great Dane",
        "Irish Wolfhound",
        "Japanese Tosa",
        "Leonberger",
        "Mastiff",
        "Newfoundland",
        "Perro de Presa Canario",
        "Pit Bull Terrier",
        "Rottweiler",
        "Saint Bernard"
    };

    private static readonly HashSet<string> LargeTrial = new(StringComparer.OrdinalIgnoreCase)
    {
        "Alaskan Malamute",
        "Belgian Shepherd",
        "Bernese Mountain Dog",
        "Bloodhound",
        "Boxer",
        "German Shepherd",
        "Giant Schnauzer",
        "Golden Retriever",
        "Greyhound",
        "Labrador Retriever",
        "Old English Sheepdog",
        "Rhodesian Ridgeback",
        "Samoyed",
        "Siberian Husky",
        "Weimaraner",
        "White Swiss Shepherd"
    };

    public const int TrialAfterNights = 5;
    public const int TrialLeadDays = 2;

    public static bool OffersSitting(string name) => !NoSitting.Contains(name.Trim());

    public static bool NeedsTrial(string name) => OffersSitting(name) && LargeTrial.Contains(name.Trim());

    public const string DeclinedMessage =
        "We are sorry — we cannot host this breed in our backyard. Asha is a young Border Collie, we keep hens, and we only sit dogs that can share that space safely.";

    public const string LargeTrialMessage =
        "We usually host smaller dogs. For a stay of five nights or more, we start with a free one-night trial at least two days before drop-off. That gives your dog time to settle, and lets us see how they go with the hens and with Asha. Some breeds have a strong hunting instinct, and we need to be sure the flock stays safe. The trial night is free, and neither of us is obliged to continue.";
}
